# Generated by Django 3.0 on 2020-05-01 01:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, help_text='Número de escuela', max_length=10, null=True)),
                ('latitud', models.FloatField(editable=False, null=True)),
                ('longitud', models.FloatField(editable=False, null=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='gestion.Distrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
            },
        ),
        migrations.CreateModel(
            name='Necesidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('LC', 'LC'), ('LE', 'LE'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], default='DNI', max_length=50, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('Masculino', 'masculino'), ('Femenino', 'femenino'), ('Otro', 'otro')], default='Masculino', max_length=20)),
                ('grado', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('vinculo', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Otro', 'Otro')], max_length=50, null=True)),
                ('apellido_reponsable', models.CharField(max_length=100)),
                ('nombre_reponsable', models.CharField(max_length=100)),
                ('tipo_documento_reponsable', models.CharField(choices=[('DNI', 'DNI'), ('LC', 'LC'), ('LE', 'LE'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], default='DNI', max_length=20)),
                ('numero_documento_reponsable', models.CharField(blank=True, max_length=30, null=True)),
                ('sexo_responsable', models.CharField(choices=[('Masculino', 'masculino'), ('Femenino', 'femenino'), ('Otro', 'otro')], default='Masculino', max_length=20)),
                ('grupo_familiar', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_solicitante', to='gestion.Escuela')),
            ],
        ),
        migrations.CreateModel(
            name='NecesidadSolicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubierta', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateField(default=datetime.date.today)),
                ('fecha_cobertura', models.DateField(blank=True, null=True)),
                ('necesidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nec_solicitante', to='gestion.Necesidad')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sol_necesidad', to='gestion.Solicitante')),
            ],
        ),
    ]
