# Generated by Django 3.0 on 2020-05-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_distrito_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='necesidad',
            options={'verbose_name': 'Opcion Necesidad', 'verbose_name_plural': 'Opcion Necesidades'},
        ),
        migrations.AlterModelOptions(
            name='necesidadsolicitante',
            options={'verbose_name': 'Necesidad', 'verbose_name_plural': 'Necesidades'},
        ),
    ]
