# Generated by Django 3.0 on 2020-05-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20200511_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='ambito',
            field=models.CharField(choices=[('Urbano', 'Urbano'), ('Rural', 'Rural')], default='Urbano', max_length=32),
        ),
        migrations.AddField(
            model_name='escuela',
            name='cue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escuela',
            name='telefono',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
