# Generated by Django 3.0 on 2020-05-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20200517_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrito', to='gestion.Distrito'),
        ),
    ]
